# Project information
site_name: DVC Template
# defeine TOC or order of website-
nav:
  - Home: index.md


site_author: Rajesh Thakur
site_description: >-
  This Repo is dedicated for generating any kind DVC projects

# Repository
repo_name: RajeshThakur1/DVC_common_template
repo_url: https://github.com/RajeshThakur1/DVC_common_template.git

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  # logo: PyTorch_logo_icon.svg

extra:
  social:


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark


plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/RajeshThakur1"  target="_blank" rel="noopener">Rajesh Kumar Thakur</a>